### ISSUE TITLE
timezone offset error after saving to db

### ISSUE THREAD

**Issue by lukeorland** [scholrly/neo4django#148] opened 2013-03-10 01:30 UTC
Once an object is written to the database, determining the timezone offset breaks.

`polls/models.py`:

``` Python
class Poll(models.NodeModel):
    question = models.StringProperty(max_length=200)
    pub_date = models.DateTimeTZProperty('date published')
```

`python manage.py shell`:

``` Python
>>> p = Poll.objects.create()
>>> p.pub_date = timezone.now()
>>> p.pub_date >= timezone.now() - datetime.timedelta(days=1)
True
>>> p.save()
>>> p.pub_date >= timezone.now() - datetime.timedelta(days=1)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439
```

**Comment by mhluongo** [comment] 2013-03-10 01:54
Funny, I just ran into this testing the auth stuff- on it. Thanks!

**Comment by mhluongo** [comment] 2013-03-10 02:27
Hm, it looks like the DateTimeTZProperty needs to be handled as Django expects- https://github.com/django/django/blob/8aefd30379eba9aa7e5afcc69cc352adf0d23489/django/db/models/fields/__init__.py#L758

**Comment by lukeorland** [comment] 2013-03-10 02:52
I was attempting to write a unit test to isolate this. In doing so, I ran `nosetests -f reg_settings.py` against the current commit in master and got 

```
FAILED (errors=9, failures=1)
```

Does this look about right to you?

**Comment by mhluongo** [comment] 2013-03-10 03:08
The numbers look right- there are a bunch of tests for future features included. If you only want to see failing regression tests, run `nosetests --with-regression neo4django/tests/`. You can add new tests to the `should_fail` list in reg_settings.py.

I think I'm going to focus on merging the DateTime and DateTimeTZProperty classes, since that looks like the preferred Django way of handling this.

**Comment by mhluongo** [comment] 2013-04-03 15:32
@lukeorland this was fixed by merging the DateTime and DateTimeTZProperty classes (7d96603c), and offloading most of the tz handling to Django util libraries. I've updated the `User` class, so if you just start using `DateTimeProperty` and either set `USE_TZ = True` in your settings, or set the local tz, you should be good.

**Closed as completed by mhluongo** 2013-04-03 15:32 UTC
